# Generated by Django 5.2.7 on 2025-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_text', models.CharField(default='BIDSOKO LUXE', help_text="Brand text displayed on the left (e.g., 'BIDSOKO LUXE')", max_length=100)),
                ('brand_text_mobile', models.CharField(default='BIDSOKO', help_text='Shorter brand text for mobile devices', max_length=50)),
                ('brand_emoji', models.CharField(default='🎯', help_text='Emoji displayed before brand text', max_length=10)),
                ('phone_number', models.CharField(default='0711 011 011', help_text='Contact phone number', max_length=20)),
                ('phone_emoji', models.CharField(default='📞', help_text='Emoji displayed before phone number', max_length=10)),
                ('announcement_text', models.CharField(default='🚚 Free Delivery on Orders Over KES 5,000', help_text='Announcement text (shown on larger screens)', max_length=200)),
                ('cta_text', models.CharField(default='SHOP NOW', help_text='Call-to-action button text', max_length=50)),
                ('cta_link', models.CharField(default='/browse', help_text="Link for the CTA button (e.g., '/browse', '/auctions')", max_length=200)),
                ('background_color', models.CharField(default='#f9e5c9', help_text='Background color (hex code or color name)', max_length=20)),
                ('text_color', models.CharField(default='#1f2937', help_text='Text color (hex code or color name)', max_length=20)),
                ('accent_color', models.CharField(default='#ea580c', help_text='Accent color for highlights (hex code or color name)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Display this promo bar on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Bar Setting',
                'verbose_name_plural': 'Promo Bar Settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
