# Generated by Django 5.2.7 on 2025-10-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobarsettings',
            name='announcement_text',
            field=models.TextField(default='🚚 Free Delivery on Orders Over KES 5,000', help_text="Announcement texts separated by '|' (pipe). Example: '🚚 Free Delivery|⚡ Flash Sale Today|🎉 50% Off Selected Items'"),
        ),
    ]
