# Generated by Django 5.2.7 on 2025-10-10 22:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for Buy Now option (leave empty for auction-only items)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='auction',
            name='product_type',
            field=models.CharField(choices=[('buy_now', 'Buy Now - Fixed Price Only'), ('auction', 'Auction - Bidding Only'), ('both', 'Both - Buy Now or Bid')], default='auction', help_text='How users can purchase this item', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Available quantity (for Buy Now items)'),
        ),
        migrations.AddField(
            model_name='auction',
            name='units_sold',
            field=models.PositiveIntegerField(default=0, help_text='Number of units sold via Buy Now'),
        ),
    ]
