# Generated by Django 5.2.7 on 2025-10-11 07:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_buy_now_price_auction_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='participation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee users pay to participate in bidding (0 for Buy Now products)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
