# Generated by Django 5.2.7 on 2025-10-12 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage for display (0-99%, purely visual)', validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='auction',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='auction',
            name='flash_sale_ends_at',
            field=models.DateTimeField(blank=True, help_text='When flash sale ends (for countdown timer)', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in hero carousel slider'),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_flash_sale',
            field=models.BooleanField(default=False, help_text='Mark as flash sale for homepage flash section'),
        ),
    ]
