# Generated by Django 5.2.7 on 2025-10-18 23:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_discount_percentage_auction_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='max_pledge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum pledge (admin sets this)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='auction',
            name='min_pledge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum pledge (admin sets this)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='round',
            name='max_pledge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum pledge amount buyers can place', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='min_pledge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum pledge amount buyers can place', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
    ]
