# Generated by Django 5.2.7 on 2025-10-20 11:00

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_allow_null_in_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='Promotional text to display', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner')),
                ('background_color', models.CharField(default='#FF6B00', help_text='Background color (hex code like #FF6B00)', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Text color (hex code like #FFFFFF)', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Banner',
                'verbose_name_plural': 'Promo Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original retail/market price (shown crossed out - like Jumia)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
