# Generated by Django 5.2.7 on 2025-10-20 14:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_promobanner_auction_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='max_pledge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum pledge (admin sets this)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='round',
            name='min_pledge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum pledge (admin sets this)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
