# Generated by Django 5.2.7 on 2025-10-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_round_max_pledge_alter_round_min_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
