# Generated by Django 5.2.7 on 2025-11-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='background_music',
            field=models.FileField(blank=True, help_text='Background music to play during the auction (MP3, WAV, etc.)', null=True, upload_to='auction_music/'),
        ),
    ]
