# Generated by Django 5.2.7 on 2026-01-11 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOfferBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Banner image (recommended: 400x200px)', upload_to='special_offers/')),
                ('link', models.CharField(default='/browse', help_text='Link URL when banner is clicked (e.g., /browse, /category/electronics)', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner in rotation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Special Offer Banner',
                'verbose_name_plural': 'Special Offer Banners',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
